apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      serviceMap:
        datasourceUid: "Prometheus"
      tracesToLogsV2:
        datasourceUid: "Loki"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags:
          - key: "service.name"
            value: "service_name"
        #customQuery: true
        #query: 'service_name="$${__resource.service.name}"'
        #query: 'method="$${__span.tags.method}"'
      tracesToMetrics:
        datasourceUid: "Prometheus"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags:
          - key: "service.name"
            value: "service_name"
        queries:
          - name: "Sample query"
            query: "sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))"
      tracesToProfiles:
        datasourceUid: "Pyroscope"
        tags:
          - key: "service.name"
            value: "service_name"
        profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
        customQuery: true
        query: 'service_name="$${__resource.service.name}"'
        #query: 'method="$${__span.tags.method}"'
      nodeGraph:
        enabled: true
